# -*- coding: utf-8 -*-
"""basit_matematik_işlemleri.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njXQW0ztAi35pQUB6_ukGcTdD7eMIpXC

**MAtematik işlemleri**
"""

#Toplama             +
#Çıkarma             -
#Çarpma              *
#Bölme               /
#Tam sayı bölmesi    //
#Kuvvet alma         **
#Mutlak değer        abs
#yuvarlama           round

"""**Karşılaştırma Operatörleri**"""

#Eşittir          ==
#Küçüktür         <
#Büyüktür         >
#Küçük eşittir    <=
#Büyük eşittir    >=
#eşit değildir    !=