# -*- coding: utf-8 -*-
"""calisma_function_def.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15dA80Mbr6lynG4nA_HXfeMkhNAN9-RgX
"""

def my_function(num1, num2):
  area = num1*num2
  print(area)

my_function(5,7)

def my_function(a, b):
    hypotenuse = (a**2 + b**2)**0.5
    print (hypotenuse)

my_function(3,4)

def longer(a,b):
  if len(a) >= len(b):
    print(a)
  else:
    print(b)
print(longer('Richard','John'))

