# -*- coding: utf-8 -*-
"""calisma_2_f_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ms4v-YzP0nBdXDmnod-5iZobm-uDmp0
"""

adi = "Enes"
 yas = 50
 f"Merhaba benim adim {adi}. Yasim {yas}"

Kisa_kenar = 5
uzun_kenar = 6
yukseklik = 12
f"Bu kutunun taban alani {Kisa_kenar * uzun_kenar} , hacmi {Kisa_kenar * uzun_kenar * yukseklik} dir."

f"sunu yazmak istiyorum {{3+5}}"

f"Merhaba benim adim {adi}. Yasim {yas if yas<40 else 'epey büyük'}"

def selam(isim):
    return "Selam " + isim

f"{selam('Betul')}, nerelerde kaldin?"

meslek = "Devops Engineer"

mesaj = f"Merhaba {adi} "\
        f"Yasim {yas} "\
        f"fakat meslegim {meslek}"

mesaj

e = 'qwerty'
n = 30

f"saga hizalama : {e:>{n}}"

f"sola hizalama : {e:<11}"

f"ortalama : {e:^25}"

f"saga hizalama : {e:*>15}"

f"sola hizalama : {e:!<11}"

f"ortalama : {e:-^25}"

for i in range(0,101,5):
    print(f'i degerimiz : {i:03}')

A = 123_456_789_123_456_789_123_456_789 # _ ile yazılsa da python sayıyı aynı alıyor

f"Sayimiz {A:,}" # , kullanılması nümerik degerlerde bir değişiklik yapmadı sadece 3'lü basamakları ayırdık

B = 255

print(f"Sayimiz : {B}")
print(f"binary system : {B:b}")
print(f"octal system : {B:o}")
print(f"hexadecimal system : {B:x}")

c = 25.859645523

f"Ondalikli sayi {c:.5f}" # .'dan sonra yazdığımız sayı ondalıklı gösterimde kaç basamak göstermesini istiyorsak o sayı olur.

d = 132254600000000000

f"Sayimizin bilimsel gösterimi : {d:e}"  # bilimsel gösterim

f"Sayimizin bilimsel gösterimi : {d:.3e}" # bilimsel gösterimde de kaç basamak görünmesini istiyorsak . sonrasına yazarak ayarlayabiliriz.

import datetime

date = datetime.datetime(2021,4,20,14,30)

date

f"Saremin dogum tarihi : {date}" # tarih formatını istediğiniz gibi değiştirebilirsiniz

f"Tarih : {date : %d*%m*%Y}" # tarih formatında neyi görmek istiyorsanız ve ne ile ayırmak istiyorsanız değiştirebilirsiniz

Sozluk = { 
        'isim' : 'Sare',
        'yas' : 2
}

f"Kizimin adı {Sozluk['isim']} yasi ise {Sozluk['yas']}"

