# -*- coding: utf-8 -*-
"""calisma_3_for_else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TL0Eq6Kr2N02OR4SHhVThM-cH1saKddb
"""

A = [1,3,5,7,9,12]

for sayi in A :
    if sayi % 2 ==0 : 
      print(f'Liste içinde kacak bir cift sayi var! Kacak sayi {sayi}') 
      break
else:
    print(f'Listenin tamami kontrol edildi herhangi bir kacak cift sayi bulunamadi.')

