# -*- coding: utf-8 -*-
"""calisma_collection_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n9wu2l1Gdc4GMPYqSo-dE0iUuwh3Y7pp
"""

country = ['USA','Canada','Germany','UK','Turkiye','Netherlands','New Zealand']

country

string_1 = "Bu cümleyi harflerine en kolay nasıl ayırırsın."
new_list_1 = list(string_1)
print (new_list_1)

new_list_2 = [string_1]
print(new_list_2)

mixed_list = [1,2,'merhaba',[20,30],True]

mixed_list

warning = 'You must quit smoking!'
print(len(list(warning)))

empty_list_1 = []
empty_list_1.append('5103')
empty_list_1.append('Apolet numaram')
print(empty_list_1)

country.append('Egypt')

country

country.insert(3,'Korea') # .append ile eklenenler hep listenin sonuna ekleniyor ancak liste arasında istediğimiz yere bu şekilde insert kullanarak eleman ekleyebiliriz.

country

country.remove('Korea')
country.sort()                # remove ile istediğimiz elemanı listeden çıkarabilir sort ile de alfabetik sıraya dizebiliriz.
print(country)

print(len(country))

#homework
my_list = [1,3,5,7]
print(my_list * 3)

country[3] = 'Belgium'
print(country)                  # bu şekilde index numarası vererek listenin istediğimiz yerine eleman atayabiliriz. Ancak atanan eleman değişmiş olur****

print(len(country))

print("The most popular country index number : ", country.index('USA'))        # index metodu ile index numarası bulma

del country[3]              # del metodu ile index numarasını bildiğimiz bir elemanı silme eğer index numarası vermezsek liste olduğu gibi silinir
print(country)

country.pop(1)          # pop metodu ile index numarasını bildiğimiz bir elemanı listeden kaldırma eğer index numarası belirtmezsek listenin son elemanı silinir.
print(country)

country_2 = ['Saudi Arabia','Qatar','Kuwait','Pakistan','Azerbaycan']

print(country_2[3])

country_2_list = []

country_2_list.append(country_2)
print(country_2_list)

country_2_list.append(country)
print(country_2_list)

print(country_2_list[1][4])                 # iç içe geçmiş listelerde istediğimiz elemanı bu şekilde yazdırabiliriz.

print(country_2_list[0][3][4])            # iç içe geçmiş listelerdeki istediğimiz elemanın istediğimiz karakterini bu şekilde yazdırabiliriz ****

"""**Homework**"""

fruits = ['apple','banana','watermelon','orange','mango','avacado']
fruit_list = []
fruit_list.insert(0,fruits)
print(fruit_list[0][2][7])

"""**Slicing a List**"""

print(country[1:4])                   # bu şekilde istediğimiz listenin istediğimiz yerlerini ayırabiliyoruz yazılan son eleman dahil olmaz burada 4. eleman dahil değil

"""**Slicing Examples**"""

numbers = list(range(0,51,2))             # range ile istediğimiz yere kadar sayıları istediğimiz aralıklarla yazdırabiliriz (2,100,2) dersek 2'den 100'e kadar olan sayıları 
                                          # 2'şer yazdırır 100 hariç
print(numbers)

print(numbers[0:15:3])                  # bu şekilde bir dizi listesi içinde hangi elemanlar arasında hangi aralıklarla giderek 
                                        # hangi elemanları yazdırmak istersek yazdırabiliriz. Bu şekilde ilk elemandan 15. elemana kadar 3 eleman atlayarak liste oluşturduk.

animals = ['elephant','giraffe','mouse','dog','horse','dolphin','deer','rabbit']
print(animals[:])
print(animals[3:])
print(animals[:5])
print(animals[::3])
print(animals[0:7:2])

even_numbers = [2,4,6,8,10,12,14,16,18,20]
print(even_numbers[4:9])

print(len([[12,34,56]]))

print(len([[12,34,56]][0]))

"""**Negative Indexing and Slicing**"""

print(even_numbers[-5])             # negatif saymalarda listenin sonundan başlanır ve -1'den saymaya başlanır.

print(even_numbers[-4:])
print(even_numbers[:-4])
print(even_numbers[::-2])
print(even_numbers[-5:-2:2])

"""**Example**"""

my_number_list = list(range(0,101))
my_even_number_list = []
my_odd_number_list = []
print(my_number_list)

for x in my_number_list:
      if x % 2 != 0:
            my_odd_number_list.append(x)
      if x % 2 == 0 :
            my_even_number_list.append(x)

print(my_odd_number_list)
print(my_even_number_list)

