# -*- coding: utf-8 -*-
"""calisma_tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vanJ_ekIVODOr0Vck_cEun0IyVPk5YBx
"""

# tuple listeleme yapmaya yarar ancak list metodundan farkı elemanları değiştirilemez oluşudur. Bu sebeple uzun kodlamalarda hata oluşmaması için tuple kullanılır
# değiştirilemez (immutable) oluşunda append() ve remove() metodları çalışmaz

empty_tuple = ()

print(type(empty_tuple))

try_tuple = ('deneme')
print(try_tuple)
print(type(try_tuple))

try_tuple = ('deneme',)
print(try_tuple)
print(type(try_tuple))              # liste içinde virgül kullandığımızda tip yine tuple'a döner

planets = ('earth','jupiter','saturn','mars','mercury')
print(planets)
print(type(planets))

empty_tuple_1 = tuple()
print(empty_tuple_1)
print(type(empty_tuple_1))

my_tuple = (1,3,5,4,3,4,3,6,9,8,4,3,6,5,2,1,4,3,6,9)
my_list = list(my_tuple)
print(type(my_list), my_list)

my_tuple = (1,3,5,4,3,4,3,6,9,8,4,3,6,5,2,1,4,3,6,9)
my_list = list(my_tuple)
print(type(my_tuple), my_tuple)

soyisim = tuple('Akbalik')          # herhangi bir string ifadeyi bu şekilde tuple haline getirebilirsiniz
print(soyisim)

mix_value_tuple = ('ART',45,True,45.45)           # tuple içerisinde farklı türden değişkenleri eleman olarak yazabilirsiniz
print(mix_value_tuple)
print(len(mix_value_tuple))

my_tuple.index(3)

my_tuple.count(6)

mix_value = (10, False, 'fruit', 1.618)
mix_value.append(['vegetable', 2+3j])
print(mix_value)
print(len(mix_value))

my_list = [4,5,2,1]
my_list.sort()
print(my_list)

"""**Example**"""

numbers = list(range(0,11))
print(numbers)
numbers.sort(reverse = True)
print(numbers)

"""**Example 2**"""

grocer = ["banana", ["orange", ["apple", "eggplant", "melon", "spinach", "cheese", "leek" ], "water"], "mandarin"]
print(grocer[1][1][1:6:2])

"""**Example 3**"""

#text = "My two favorite flowers are tulip and rose, two favorite colors are blue and green."

flowers = [["jasmine", ["lavender", "rose"], "tulip"]]
colors = ["red", ["blue", ["yellow", "green"]], "pink"]
text = "My two favorite flowers are {a} and {b}, two favorite colors are {c} and {d}."
print(text.format(a = flowers[0][2] , b = flowers[0][1][1], c = colors[1][0], d = colors[1][1][1]))

"""**Example 4 **"""

#I am 40 years old.
    #I have two children.
        #Data Science is my IT domain.

escapes = ["\n\t", ("\t", "\t\t"), ["\n", "\n\t\t"]]

sentence = "I am 40 years old.{}I have two children.{}Data Science is my IT domain."

print(sentence.format(escapes[0] , escapes[2][1]))

