# -*- coding: utf-8 -*-
"""dictionaries_calisma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3LJ0-LlwR2Zn_hcgGohbt5kfFgVuGWj
"""

empty_dict_1 = {}
empty_dict_2 = dict()

print(type(empty_dict_1))

yasadigim_yerler={'Ankara':'Kecioren',
         'İzmir':'Gaziemir',
         'Mardin':'Merkez',
         'Amasya':'Merizfon',
         'Manisa':'Yunusemre',
         'Kocaeli':'Izmit'}

print(yasadigim_yerler['Kocaeli'])

yasadigim_yerler['Ankara_2']='Cankaya'            #Yeni eleman ekleme
print(yasadigim_yerler)

mix_values = {'hayvan':('at','kopek'),
              'muzik':['rock','jazz','classic'],
              'yas':29,
              'plaka':35.5,
              'all_is_well': True}

dict_by_dict = dict(hayvan='at',muzik='rock',numara=45,Plaka=35.5,all_is_well=True)      #karışık tipler ile kendimiz de

print(dict_by_dict)

print(mix_values.items(), '\n')
print(mix_values.keys(), '\n')
print(mix_values.values())                                # sözlük içindeki anahtarları ve değerleri ayrı ayrı da yazdırabiliriz beraber de

yasadigim_yerler.update({'Izmir_2': 'Guzelbahce'})                 # update komutu ile herhangi bir eleman eklenebilir
print(yasadigim_yerler)

del mix_values['all_is_well']             # del komutu ile istediğimiz elemanı silebiliriz hem key hem value
print(mix_values)

print('Ankara' in yasadigim_yerler)
print('hayvan' in mix_values)                     # sözlük içerisinde key var mı diye in komutu ile sordurulabilir.

school_records={
    "personal_info":
        {"kid":{"tom": {"class": "intermediate", "age": 10},
                "sue": {"class": "elementary", "age": 8}
               },
         "teen":{"joseph":{"class": "college", "age": 19},
                 "marry":{"class": "high school", "age": 16}
               },               
        },
        
    "grades_info":
        {"kid":{"tom": {"math": 88, "speech": 69},
                "sue": {"math": 90, "speech": 81}
               },
         "teen":{"joseph":{"coding": 80, "math": 89},
                 "marry":{"coding": 70, "math": 96}
               },               
        },        
}

print(school_records['grades_info']['kid']['sue']['speech'])

"""**Homework**"""

#JSON (JavaScript Object Notation), veri depolamak ve alışverişi yapmak için yazılan bir sözdizimidir.

