# -*- coding: utf-8 -*-
"""kahve_maliyet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WF49yZwcOzAZ0e6WEjswZMSDh2Yto8Oi
"""

k = float(input("Kahveyi ne kadara aldiniz : "))
kg = float(input("Kaç gram kahve aldiniz : "))
s = float(input("Bir damacana suyu ne kadara alıyorsunuz : "))
t = float(input("Filtre kağıdını kaçlı aldiniz : "))
l = float(input("Filtre kağıdını ne kadara aldiniz : "))

a = (((k*1000)/k)/1000)*7         #7 gram kahve fiyatı (1 porsiyon)
b = (s/19)/4                      #250 ml su fiyatı
c = l/t                           # 1 tane filtre kağıdı ücreti
tutar = a+b+c
print(f"Evde yapilan bir fincan filtre kahve {tutar:.2f} liraya mal oluyor.")

