# -*- coding: utf-8 -*-
"""odev_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvBWkrDXhyEtixZZdcUrT5LUX3SsZdiZ
"""

temp_cel = float(input("Sıcakligi Celcius cinsinden giriniz : "))
temp_fah = (temp_cel*1.8)+32
print(f"Sicaklik {temp_fah} fahrenheit ")

mea_km = float(input("Mesafeyi km cinsinden giriniz : "))
mea_ml = mea_km * 0.621371
print("Mesafe %0.2f mildir." %(mea_ml))

