# -*- coding: utf-8 -*-
"""PYTHON_WS_numbers_booleans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmnVXZMWouWu5-nSQEV_x3Oz1pXSMcVR

<p>Given the code below, use the correct function on line 3 in order to convert <strong>num1 </strong>from integer to float.</p>
"""

num1 = 25

num2 = 

print(type(num2))

"""<p>Given the code below, use the correct function on line 3 in order to convert <strong>num1 </strong>from float to integer.</p>"""

num1 = 13.67

num2 = 

print(type(num2))

"""<p>Given the code below, use the correct math operator in between <strong>num1 </strong>and <strong>num2 </strong>on line 4 in order to obtain the result shown.</p>"""

num1 = 25
num2 = 8

num3 = num1 num2

print(num3 == 1) #result is True

"""<p>Given the code below, use the correct math operator in between <strong>num1 </strong>and <strong>num2 </strong>on line 4 in order to obtain the result shown.</p>"""

num1 = 10
num2 = 3

num3 = num1 num2

print(num3 == 250 * 4) #result is True

"""<p>Given the code below, use the correct math operator in between <strong>num1 </strong>and <strong>num2 </strong>on line 4 in order to obtain the result shown.</p>"""

num1 = 5
num2 = 2

num3 = num1 num2

print(num3 == 5 % 3) #result is True

"""<p>Given the code below, use the correct function<strong> </strong>on line 3 in order to obtain the distance between <strong>num1 </strong>and 0.</p>"""

num1 = -11

num2 = 

print(num2 == 11) #should result in True

"""<p>Given the code below, use the correct function<strong> </strong>on line 4 in order to raise <strong>num1 </strong>to the power of <strong>num2</strong>.</p>"""

num1 = 10
num2 = 5

num3 = 

print(num3 == 100000)

"""<p>Given the code below, use the correct logical operator in between the two expressions<strong> </strong>on line 1 in order for the final result to be <strong>False</strong>.</p>"""

result = ((25 % 7 + 10 / 2) % 3 == 0)  ((abs(-19) / 2 - 2) > 9)

print(result) #should return False

"""<p>Given the code below, use the correct logical operator in between the two expressions<strong> </strong>on line 1 in order for the final result to be <strong>True</strong>.</p>"""

result = (min(pow(2, abs(3)), 9) == 3 ** 2 - 1)  (66 % 20 + 2 > 2 ** 3)

print(result) #should return True

"""<p>Given the code below, use the correct function on line 1 (for which the argument sits inside the parentheses) in order for the final result to be <strong>False</strong>.</p>"""

result = (150 % (10 ** 2 / 2))

print(result) #should return False