# -*- coding: utf-8 -*-
"""Sets_calisma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1__ZYJRa_Tl72c45AaBCvm41UyKVjxevh
"""

# {} ya da set() fonksiyonları ile kullanılır
# boş bir set kurmak istiyorsak sadece onda set() ile kurma zorunluluğumuz var çünkü boş bir {} ile boş bir dict kurabiliriz

empty_set = set()

print(type(empty_set))

renkset={'mor','turuncu','kirmizi','yesil','sari','siyah','beyaz','mavi','sari'}

print(renkset)
print(renkset)                # listemizde 2 sari olmasina ragmen yazdirirken tek sari yazdirildi. Set'in en baz özelliği tekrarların önüne gecmesidir.

k = set('cekoslavakyalılastıramadıklarimiz')
print(k)
len(k)

print(len(set('listen to the voice of enlisted')))

numbers = {}

numbers['x'] = 12
numbers['y'] = 4
numbers.update({'z': 3})

print(numbers['x'] + numbers['y'] + numbers['z']**2)

fruits_vegetables = ["fruit", "vegetable", ["apple", "banana", ["mango", "avocado"]], ["spinach", "broccoli"]]
print(fruits_vegetables[3][0])

