# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCJg44AHxne-Qu1PhpSLUJg4LQsuXpzc
"""

def draw_tree(levels, branches):
    # Çizilecek maksimum dal uzunluğunu hesaplayın
    max_branch_length = 2 * branches - 1

    # Her seviyede satır sayısını hesaplayın
    row_count = levels * 2 - 1

    # Ağacı çizin
    for i in range(row_count):
        # Bu satırın dal sayısını hesaplayın
        branch_count = branches + (i - levels + 1)

        # Her dala bir satır yazdırın
        for j in range(branch_count):
            # Dalların arasındaki boşlukları hesaplayın
            space_count = max_branch_length - (2 * j - 1)
            spaces = " " * (space_count // 2)

            # Gövdeyi ve dalları yazdırın
            if j == 0:
                print(spaces + "*" * 1)
            else:
                print(spaces + "*" * (2 * j - 1) + "|")

# Kullanıcıdan kat sayısı ve dal sayısı alın
levels = int(input("Kaç katlı bir ağaç çizmek istiyorsunuz? "))
branches = int(input("Her seviyede kaç dal olsun? "))

# Ağacı çiz
draw_tree(levels, branches)

